### PR TITLE
Add black gradient & elevation to card view

### LINKED ISSUE #107: [Feature Request / Suggestion]: Add black gradient & elevation to card view
### Suggestion / Feature Request

By adding black gradient to the title of the card view, and applying a little bit of elevation, makes the card view more visually appealing

Please assign me this task. Would be happy to contribute :)

Screenshot_2022-10-22-11-38-47-763_com pec_acm moviedroid

### PR DESCRIPTION
**Pull request by its-me-debk007**
## Description

Added black gradient to of the CardView and implemented elevation to CardView for better visual experience. Also updated the dependencies and gradle.

## Issue Resolved

Fixes #107

## Screenshots 

Screenshot_2022-10-22-18-19-18-461_com pec_acm moviedroid

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Great work @its-me-debk007 😄 please remove the changes made in the gradle files they are not required 😅

**Comment by its-me-debk007** [comment]
Got it! Should I also revert back the dependencies to their previous versions?

**Comment by ken1000minus7** [comment]
Yes

**Comment by its-me-debk007** [comment]
Done!

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Seems good 😄 , remove all the other changes in the two `build.gradle` files and the `AndroidManifest.xml` file as well, then your pr will be ready to be merged 😇

**Comment by its-me-debk007** [comment]
All changes have been implemented!

**Review by ken1000minus7 — APPROVED** [review]

**Comment by ken1000minus7** [comment]
Lgtm gw 😇

**Comment by its-me-debk007** [comment]
Thanks :)

**Pull request merged**
