### PR TITLE
Sorted individual list

### LINKED ISSUE #100: Sort individual lists
### Suggestion / Feature Request

The all list is sorted, sort the the other individual lists as well according to name

### PR DESCRIPTION
**Pull request by Chandra-Sekhar-Bala**
## Description

Sorted individual lists, so the data could be shown in a well-mannered form.

## Issue Resolved

'Fixes #100 

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Het @Chandra-Sekhar-Bala , these lists don't need to be sorted, you need to sort the eatching, completed, plan to watch , on hold and dropped lists 😅 Just remove the sorting done here and it to those lists 😇

**Comment by Chandra-Sekhar-Bala** [comment]
Thanks for the details @ken1000minus7. I should have asked for exact changes tho.  Anyway, I'll make a PR asap :-)

**Review by ken1000minus7 — APPROVED** [review]

**Comment by ken1000minus7** [comment]
Lgtm gw 😇

**Comment by Chandra-Sekhar-Bala** [comment]
Thanks, @ken1000minus7  :)

**Pull request merged**
