### PR TITLE
Converted the remaining java files to kotlin

### LINKED ISSUE #70: Migrate remaining Java files to Kotlin
### Suggestion / Feature Request

Let's remove java completely :) 

After migrating, remove the java badge from readme 😇

### PR DESCRIPTION
**Pull request by krishnachaitanya0107**
Converted the following files from java to kotlin 

- ExampleInstrumentedTest.java
- ExampleUnitTest.java

### CODE REVIEW

**Comment by krishnachaitanya0107** [comment]
Related issue https://github.com/PEC-CSS/MovieDroid/issues/70

**Comment by ken1000minus7** [comment]
Lgtm, thanks for your contribution! 😄

**Comment by ken1000minus7** [comment]
🥳 
image

**Comment by krishnachaitanya0107** [comment]
Thank you @ken1000minus7  , Oops 😅 Sorry looks like i totally forgot about removing java from readme file .

**Comment by ken1000minus7** [comment]
No prob 😇

**Pull request merged**
