### PR TITLE
Added ISSUES_TEMPLATE & Migrated Login Activity To Kotlin

### LINKED ISSUE #46: Migrate `LoginActivity` to Kotlin
Currently the `LoginActivity` is written in Java. Migrate the Java code to Kotlin.

### PR DESCRIPTION
**Pull request by RahulSoni0**
## Description
created new issues template & Migrated LoginActivity to Kotlin

## Issue Resolved

fixed Create an issue template #15 and Fixed #46

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by RahulSoni0** [comment]
once check this much information is good to go for a issue creation?

**Comment by RahulSoni0** [comment]
sorry raised pr for both issue at once . can you please merge only first #15 as #46 i want to verify it once again?

**Comment by RahulSoni0** [comment]
I will create a separate pr

**Comment by ken1000minus7** [comment]
@RahulSoni0 Sure, try to resolve the issues in separate branches so that you can make multiple prs at the same time 😇

**Pull request closed without merging**
