### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by uttammittal02**
## Description

Added the ML Model

## Issue Resolved

Link to the issue that is resolved by this pull request goes here e.g. 'Fixes # 10'.

## Screenshots 

Provide some screenshots of the changes made (if applicable).

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
@uttammittal02 Make those changes then lemme know when done, also look into this once if we can implement it https://www.tensorflow.org/lite/examples/on_device_training/overview

**Comment by yellowHatpro** [comment]
@uttammittal02 Thanks for the work😍..
Please also create a .gitignore file  to prevent uploading unnecessary clutter

**Comment by ken1000minus7** [comment]
@uttammittal02 gw, just add a gitgnore for all the unnecessary files (like pycache and all) and ur pr will be ready to be merged :yum:

**Comment by ken1000minus7** [comment]
@uttammittal02 sadge, make new pr

**Pull request closed without merging**
