### PR TITLE
added shimmer effect in homefragment

### LINKED ISSUE #169: use shimmer effect in mainactivity while data loads
here

### PR DESCRIPTION
**Pull request by armaanbadhan**
## Issue Resolved

fixes #169 

## Screenshots 

https://user-images.githubusercontent.com/66007619/222669670-3d450df8-b312-4a27-b866-95d26e6f3274.mp4

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ken1000minus7** [comment]
Lgtm, why draft pr though

**Comment by armaanbadhan** [comment]
i just added that to top movie top tv and popular movie, last three are left should i skip them?

**Comment by ken1000minus7** [comment]
Well better to add to all

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
