### PR TITLE
* Added remove rating option to list view of ScoreBottomSheet.kt

### LINKED ISSUE #104: Add option to remove rating given to a movie/TV show
### Suggestion / Feature Request

The score bottom sheet contains no option to remove rating, add an option for it. On removing the rating, score property of the user should be set to 0

### PR DESCRIPTION
**Pull request by bharadwajmsr**
## Description

* Added remove rating option to list view of ScoreBottomSheet.kt 

## Issue Resolved

```Fixes #104 ```.

## Checklist

Please make sure to review the following before submitting your PR: 

- [x ] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [ x] I have read the code of conduct.
- [ x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by prasad-333** [comment]
looks good to me.

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Hey @bharadwajmsr , you also need to add a condition here that when i is 10, the item should be removed from the user's list in firebase

https://github.com/PEC-CSS/MovieDroid/blob/38d03fa2e0ddf6aed75ffd3fcccb0f624d0eca4c/app/src/main/java/com/pec_acm/moviedroid/mainpage/list/ScoreBottomSheet.kt#L38-L43

**Comment by bharadwajmsr** [comment]
You mean ?
`statusList.setOnItemClickListener { adapterView, view, i, id -> 

     if (10 - i != listItem.personalScore) { 
         listViewModel.setItemScore(FirebaseAuth.getInstance().uid!!, listItem.id, 10-i) 
          if (10 == i) {
          listViewModel.removeItem(FirebaseAuth.getInstance().uid!!, listItem)
         }
     }`

**Comment by ken1000minus7** [comment]
Yes, just put the set item score line in else statement like this
```kt
if (10 == i) {
      listViewModel.removeItem(FirebaseAuth.getInstance().uid!!, listItem)
}
else {
     listViewModel.setItemScore(FirebaseAuth.getInstance().uid!!, listItem.id, 10-i)
}
```

**Comment by bharadwajmsr** [comment]
@ken1000minus7 Shouldn't it be else if as original code avoids updating the list if user choose existing rating? I assume below works 
```
if (10 == i )  {
      listViewModel.removeItem(FirebaseAuth.getInstance().uid!!, listItem)
} else if (10 - i != listItem.personalScore) {
     listViewModel.setItemScore(FirebaseAuth.getInstance().uid!!, listItem.id, 10-i) 
}
```

**Comment by ken1000minus7** [comment]
Yeah actually the whole if else was supposed to be inside that if condition, but this works too

**Comment by bharadwajmsr** [comment]
@ken1000minus7 Pushed required changes. Please review it

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
