### PR TITLE
Added colors for night mode view.  Fixes #41

### LINKED ISSUE #41: Add colors for Night mode
Add suitable colors for night mode in the night colors.xml file and corresponding light mode colors in the original colors.xml and use the colors wherever required. Each color in the night colors.xml should have the same name as their light mode counterpart in the original colors.xml. 

Like for example
In the original colors.xml
```xml
<color name="text_color">#000000</color>
```
Then subsequently in the night colors.xml
```xml
<color name="text_color">#FFFFFF</color>
```
<details> 
  <summary>PS</summary>
  This is just an example, all the colors of the app need to be added and not just this (probably don't even need to add this)
  </details>

### PR DESCRIPTION
**Pull request by AndroidLion48**
## Description

[Describe](https://github.com/PEC-CSS/MovieDroid/issues/41) the changes you have made.

## Issue Resolved

Link to the issue that is resolved by this pull request goes here e.g. 'Fixes #41'.

## Screenshots 

Provide some screenshots of the changes made (if applicable).

## Checklist

Please make sure to review the following before submitting your PR: 

- [X] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [X] I have read the code of conduct.
- [X] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by AndroidLion48** [comment]
Please remember to add #Hacktoberfest-accepted to my PR labels.

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Hey @AndroidLion48 , u hv added a style in the night `colors.xml` , we just need the corresponding night mode colors there, also don't remove color already present there 😇

**Comment by AndroidLion48** [comment]
I replaced the "searchBar" color that was removed, updated the night themes appropriately, and added the night colors to the night colors.xml.

**Review by ken1000minus7 — APPROVED** [review]

**Comment by ken1000minus7** [comment]
Lgtm, thanks for your contribution 😄

**Pull request merged**
